/* 
**  mod_SmartHome.c -- Apache sample SmartHome module
**  [Autogenerated via ``apxs -n SmartHome -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_SmartHome.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /SmartHome in as follows:
**
**    #   httpd.conf
**    LoadModule SmartHome_module modules/mod_SmartHome.so
**    <Location /SmartHome>
**    SetHandler SmartHome
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /SmartHome and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/SmartHome 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_SmartHome.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"
#include "../../SHP.h"
#include <signal.h>

#undef DBG
#define DBG printf

////////////////////////////////////////////begin/////////////////////////////
#include <pthread.h>
#include <sys/socket.h>
extern void shp_dbg_mem(char *data, int len);
static int server_control_network_send(char* bin,int size);
typedef struct POSTDATA_T
{
	int len;
	char data[4096];
}POSTDATA_T;
typedef struct SystemInfr
{
	pthread_t	network_thread_id;
	int 		soc_id;
	POSTDATA_T  post_data;
}SystemInfr;
SystemInfr sys;
static POSTDATA_T* SmartHome_handler_get_post_data(request_rec *r);
//#define SERVER_CONTROL_IP	"10.239.206.36"
#define SERVER_CONTROL_IP	"127.0.0.1"
#define SERVER_CONTROL_PORT	9596
///////////////////////////////////////////////end///////////////////////////

/************JUST FOR TEST******************begin**************************/
static int SmartHome_TEST(request_rec *r)
{
	printf("\r\n===========================test=====begin==================\r\n");
	shp_dbg_mem(r,sizeof(request_rec));
	printf("request_rec->the_request=%s\r\n",r->the_request);
	printf("request_rec->protocol=%s\r\n",r->protocol);
	printf("request_rec->hostname=%s\r\n",r->hostname);
	printf("request_rec->status_line=%s\r\n",r->status_line);
	printf("request_rec->method=%s\r\n",r->method);
	printf("request_rec->range=%s\r\n",r->range);
	printf("request_rec->clength=%d\r\n",r->clength);
	printf("=====shp_dbg_mem(r->range,r->clength)=======\r\n");
	shp_dbg_mem(r->range,r->clength);
	printf("request_rec->user=%s\r\n",r->user);
	printf("request_rec->ap_auth_type=%s\r\n",r->ap_auth_type);
	printf("request_rec->unparsed_uri=%s\r\n",r->unparsed_uri);
	printf("request_rec->uri=%s\r\n",r->uri);
	printf("request_rec->filename=%s\r\n",r->filename);
	printf("request_rec->canonical_filename=%s\r\n",r->canonical_filename);
	printf("request_rec->path_info=%s\r\n",r->path_info);
	printf("request_rec->args=%s\r\n",r->args);
	/******ap_get_client_block***test*****begin**/{
	POSTDATA_T* post_data = SmartHome_handler_get_post_data(r);
	shp_dbg_mem(sys.post_data.data,sys.post_data.len);
	/******ap_get_client_block***test*****end*****/}
	
	printf("\r\n===========================test=====end==================\r\n\r\n\r\n");

}
/************JUST FOR TEST******************end****************************/

S16  server_control_network_send_package(S8 type,void* bin,S16 len)
{
	int ret = 0;
	SHP_HeadForSend	head={SHP_MAGIC1,sizeof(SHP_HeadForSend),SHP_MAGIC2,type,0};
	head.pkg_len+=len;
	server_control_network_send(&head,sizeof(head));
	ret = server_control_network_send(bin,len);
	DBG("strerrno = %s\r\n",errno);
	return ret;
}

static POSTDATA_T* SmartHome_handler_get_post_data(request_rec *r)
{
	int  ret = 0;
	int  pos = 0;
	ret = ap_setup_client_block(r,REQUEST_CHUNKED_ERROR);
	printf("request_rec->ap_setup_client_block() = %d\r\n",ret);	
	printf("request_rec->ap_get_client_block()\r\n");
	pos = 0;
	while((ret = ap_get_client_block(r,sys.post_data.data+pos,sizeof(ap_get_client_block)))>0){
		pos+=ret;
	}
	sys.post_data.len = pos;
	return &sys.post_data;
}

static void SmartHome_handler_handle_post_data(POSTDATA_T* post)
{
	char* p 	= post->data;
	int   len	= post->len;
	
	if(len<2){
		DBG("The post data is too short to handle,Skiped!!!!!\r\n");
		return ;
	}
	
	////JUST json string//////////////////
	if(*p=='{' && *(p+len-1)=='}'){
		server_control_network_send_package('J',p,len);
	////JUST xml string///////////////////
	}else if(*p=='<' && *(p+len-1)=='>'){
		server_control_network_send_package('X',p,len);	
	////head + json/xml string////////////
	}else if(*p==SHP_MAGIC1 && *(p+2)==SHP_MAGIC2){
		server_control_network_send(p,len);	
	}else{
		DBG("Unknow package!!!!!!!!\r\n");
	}
	return;
}

/* The sample content handler */
static int SmartHome_handler(request_rec *r)
{
    printf("SmartHome r->handler=%s\r\n",r->handler);
    printf("System infr:\r\n\tnetwork_thread_id=%d\r\n\tsoc_id=%d\r\n",sys.network_thread_id,sys.soc_id);
	#if 0
		SmartHome_TEST(r);
	#else
		POSTDATA_T* post_data = SmartHome_handler_get_post_data(r);
		shp_dbg_mem(sys.post_data.data,sys.post_data.len);
		SmartHome_handler_handle_post_data(post_data);
	#endif
    if (strcmp(r->handler, "smarthome")) {
        return DECLINED;
    }
    r->content_type = "text/json";      

    if (!r->header_only)
        ap_rputs("The sample page from mod_SmartHome.c\n", r);
		
    return OK;
}

static void* server_control_network_thread(void* arg);
static int isRunning = 0;
static void SmartHome_register_hooks(apr_pool_t *p)
{	
	
    ap_hook_handler(SmartHome_handler, NULL, NULL, APR_HOOK_MIDDLE/*APR_HOOK_REALLY_FIRST*/);
	/************start thread*****begin******************/{
    extern void start_smarthome_service(void);
    if(isRunning==0){
		int ret = 0;
		isRunning = 1;
		ret = pthread_create(&sys.network_thread_id,NULL,server_control_network_thread,NULL);
		if(ret!=0){
			sys.network_thread_id = 0;
			isRunning = 0;
			printf("Create net work thread failed!!!!!!!!\r\n");
		}
	}else{
		isRunning = 0;
		if(sys.network_thread_id){
			printf("Kill network thread!!!!!!!!\r\n");
			pthread_kill(sys.network_thread_id, SIGALRM);
		}
	}
	/************start thread*****end********************/}
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA SmartHome_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    SmartHome_register_hooks  /* register hooks                      */
};


/******************************************************************************
 * FUNCTION NAME:	server_control_network_send
 * --------------------
 *    2013/09/06, Q.Bryan create this function
 ******************************************************************************/
static int server_control_network_send(char* bin,int size)
{
	int ret = send(sys.soc_id,bin,size,0);
	if(ret < 0){
		DBG("Send error!!!\r\n");
	}else{
		DBG("Send %d bytes data!!!\r\n",ret);	
	}
	return ret;
}

void server_control_network_thread_signal_func(int sig)
{
	if(sig==SIGKILL){
		printf("server control network thread killed!!!!!!!\r\n");
		close(sys.soc_id);		
	}else{
		printf("server_control_network_thread_signal_func  **be called***\r\n");	
	}
	return ;
}

/******************************************************************************
 * FUNCTION NAME:	server_control_thread
 * DESCRIPTION:		This is a thread function for listen PORT;
 					After accept a connect create a socket thread to handle the data
 * --------------------
 *    2013/09/06, Q.Bryan create this function
 ******************************************************************************/
static void* server_control_network_thread(void* arg)
{
	/*----------------------------------------------------------------*/
	/* Local Variables                                                */
	/*----------------------------------------------------------------*/
    struct sockaddr_in server_addr;
	int ret = 0;
	static char	soc_recv_buffer[2048];
	/*----------------------------------------------------------------*/
	/* Code Body                                                      */
	/*----------------------------------------------------------------*/
	signal(SIGKILL,server_control_network_thread_signal_func);
	//initialize
    bzero(&server_addr,sizeof(server_addr));
    server_addr.sin_family 		= AF_INET;
    server_addr.sin_addr.s_addr = inet_addr(SERVER_CONTROL_IP);
    server_addr.sin_port		= htons(SERVER_CONTROL_PORT);
	
	while(1){
		//create
		printf("Create socket...\r\n");
		if(sys.soc_id)close(sys.soc_id);
		sys.soc_id = socket(PF_INET,SOCK_STREAM,0);
		if( sys.soc_id > 0){
			printf("Create socket success\r\n");
		}else{
			printf("Create Socket Failed!\r\n");
			sys.soc_id = 0;
			sleep(10);
			continue;
		}

	
		printf("Connecting server host...\r\n");
		//connect
		ret = connect(sys.soc_id,&server_addr,sizeof(server_addr));
		if(ret < 0){
			printf("Connect server host failed!!!!\r\n");
			close(sys.soc_id);
			sleep(10);
			continue;			
		}
		printf("Connect server host success!\r\n");

		/////////test///////begin///////
		//while(server_control_network_send("ABC",4)>0){sleep(1);}break;
		/////////test///////begin///////
		
		printf("Recv server data...\r\n");		
		while(1){
			//recv
			ret = recv(sys.soc_id, soc_recv_buffer, sizeof(soc_recv_buffer), 0);
			if(ret < 0){
				printf("recv error,retry...!!!!\r\n");
				close(sys.soc_id);
				sleep(1);
				break;				
			}else if(ret == 0){
				printf("recv timeout,retry...!!!!\r\n");
				close(sys.soc_id);
				sleep(1);
				break;				
				//continue;
			}else if(ret > 0 ){
				printf("!!!!!!!recieved %d bytes data...!!!!\r\n",ret);			
				shp_dbg_mem(soc_recv_buffer,ret);
				printf("!!!!!!!All %d bytes data done!!!!\----------------------\r\n",ret);			
			}
		}
	}
	return 0;
}


#define LINE_SIZE 16
void shp_dbg_mem(char *data, int len)
{
	static int	shp_dbg_mem_called_count = 0;
	static const char *displayble_chars = 
		"abcdefghijklmnopqrstuvwxyz"
		"ABCDEFGHIJKLMNOPQRSTUVWXYZ"
		"0123456789"
		")!@#$%^&*(`-=~_+"
		"[]{}\\|;':\""
		",./<>?";
	int i = 0;
	char line[LINE_SIZE];
	int j = 0;
	printf(">>>%d>>>>\r\nnow dump %d bytes memory from %p\r\n",shp_dbg_mem_called_count++,len, data);
	if (len <= 0)
		return;
	for (i = 0; i < len; i++)
	{
		line[i % LINE_SIZE] = data[i];
		if (i % LINE_SIZE == 0)
			printf("%08x: ", i);
		printf("%02x ", data[i]);
		if ((i + 1) % LINE_SIZE == 0)
		{
			for (j = 0; j < LINE_SIZE; j++)
			{
				unsigned char c = '.';
				if (strchr(displayble_chars, line[j]))
					c = line[j];
				if (c == 0)
					c = '.';
				printf("%c", c);
			}
			printf("\r\n");
		}
	}
	//print the last line
	if (len % LINE_SIZE != 0)
	{
		for (i = 0; i < LINE_SIZE - len % LINE_SIZE; i++)
		{
			printf("   ");
		}
		for (i = 0; i < len % LINE_SIZE; i++)
		{

			unsigned char c = '.';
			if (strchr(displayble_chars, line[i]))
				c = line[i];
			if (c == 0)
				c = '.';
			printf("%c", c);
		}
	}
	printf("\r\n----------------------\r\n");	
}

